# Generated by Django 2.0.6 on 2019-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessmodel',
            name='calories',
            field=models.IntegerField(default=''),
        ),
    ]
